### ISSUE TITLE
the action is very stupid, i suggest you close this repo

### ISSUE THREAD

**Issue by googya** [fluttercandies/no-free-usage-action#11]
if a user found some issues, and feedback to the repo's owner, is not that a good thing? Why is there a requirement for the person finding a issue? that's absurd! 

if that person did not star or fork repo but sponsored the project， how about that?

i am afraid this repo shows you has not understood oss and also your narrow-mindedness.

do the right thing, close it!

**Comment by AlexV525** [comment]
Before you make your conclusion, I want to ask more question:
* How many time did you spend on open source?
* How many issue did you open on other repo?
* Have you ever get a request for non-documented?
* Isn't this action provide options to choose fork or star?

For those users who truly wants to bring bugs and questions to the repo. I can manually unlock them and put `valid issue` label. But for other people (especially someone like you, only 26 contribution over the year), I can block them without any manual progress.

You may not understand what's happening in the open source community, and I suggest you take more time to contribute before you say something like this.
